name: pose6d
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch-cuda=13.0
  - pytorch=2.9.1
  - torchvision=0.24.1
  - numpy=2.2.6
  - scipy=1.15.2
  - matplotlib=3.10.8
  - pillow=12.0.0
  - pyyaml=6.0.3
  - tqdm=4.67.1
  - pip
  - pip:
    - ultralytics==8.3.237
    - opencv-python==4.12.0.88